Repository knapsack-cloud/twig-renderer, pull requests merged in 2023-11, with the labels that each got.

#112 setup better npm publishing
  .github/workflows/push.yml
  auto.config.js
  package-lock.json
  package.json
  prettier.config.cjs
  release.config.js
Labels: patch

#117 Update PHP project dependencies.
  composer.lock
Labels: patch

#118 Fix deprecations
  __tests__/twig-extensions/alter-twig.php
  src/TwigRenderer.php
  src/server--async.php
Labels: minor

#120 fix CI publish
  .github/workflows/push.yml
Labels: internal

#119 Php code cleanup
  __tests__/twig-extensions/alter-twig.php
  src/TwigRenderer.php
  src/server--async.php
  src/server--sync.php
Labels: patch

#121 Add tools for and and apply coding standards
  .editorconfig
  .gitignore
  .php-cs-fixer.dist.php
  __tests__/twig-extensions/alter-twig.php
  composer.json
  composer.lock
  src/TwigRenderer.php
  src/server--async.php
  src/server--sync.php
Labels: internal

#122 Update Twig to version 3.
  composer.json
  composer.lock
Labels: major

#123 Move php-cs-fixer to tools directory.
  .gitignore
  composer.json
  composer.lock
  tools/php-cs-fixer/composer.json
  tools/php-cs-fixer/composer.lock
Labels: patch
