Repository knapsack-cloud/twig-renderer, pull requests merged in 2024-01, with the labels that each got.

#92 Delegate rendering to environment
  src/TwigRenderer.php
Labels: patch

#127 Update packages with npm audit.
  package-lock.json
Labels: dependencies, javascript, minor

#126 Update react/http to current release.
  composer.json
  composer.lock
  src/server--async.php
Labels: dependencies, php, minor

#134 Updates minor package version for JS deps.
  package-lock.json
  package.json
  src/twig-renderer.js
Labels: dependencies, javascript, patch

#137 Updates minor package version for more JS deps.
  package-lock.json
  package.json
Labels: dependencies, javascript, patch
